development:
  host: localhost
  database: show_alerts_development

test:
  host: localhost
  database: show_alerts_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
